---
- hosts: webservers
  become: true
  vars:
    create_containers: 1
    default_container_name: my-app
    default_container_image: cloudhight/pipeline:1.0.9
    default_container_command: sleep 1d
    default_container_port: 8080
    defaul_host_port: 8080

  tasks:
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull
    - name: Stop a container
      docker_container:
        name: my-app
        state: absent
    - name: Restart a container
      docker_container:
        name: my-app
        image: cloudhight/pipeline:1.0.9
        state: started
        ports:
         - "8080:8080"